web:
  build: .
  ports:
    - "80:5000"
  volumes:
    - /usr/src/app/static
  links:
    - mongodb
  env_file: .env
  environment:
    TW_MONGODB_DB: "tweet_wall"
    TW_MONGODB_HOST: mongodb
  command: python run.py
mongodb:
  ports:
    - "27017:27017"
  image: mongo:3.0.5
  command: mongod --smallfiles --nojournal --noprealloc
